### PR TITLE
Mccs JSON parsing

### PR DESCRIPTION
**Pull request by frett**
addresses #46 depends on #73

### CODE REVIEW

**Comment by frett** [comment]
@wrandall22 @mattfred last one from me until at least Wednesday, sitting at the airport right now :)

**Comment by wrandall22** [comment]
Outside of my comment, looks good.

**Comment by frett** [comment]
Unfortunately there is no `ALTER TABLE DROP COLUMN` in SQLite, the only way to remove the columns is build a new table, copy the DAT, delete the old, rename the new to the old

**Comment by frett** [comment]
So, leaving them there doesn't hurt anything unless you want to reuse the column name later.

**Pull request merged**
