### PR TITLE
Assignment update

### PR DESCRIPTION
**Pull request by frett**
This update includes the following major changes

* Updated Assignment model to be indexed on GUID and ministry_id
* Track the selected MCC in the currently selected Assignment
* Create an Assignment loader that will load the current assignment (and optionally the ministry for that assignment)
* changed how assignments json is parsed, subMinistries are now parsed as subAssignments to support extracting assignment data from sub ministries
* replaced SettingsActivity with support library aware version that utilizes ContentLoaders to populate options

### CODE REVIEW

**Comment by frett** [comment]
@wrandall22 @mattfred 

I didn't update MCC usage in the MeasurementsActivity because it would probably conflict quite a bit with @wrandall22 's current PR. And there is already plenty of conflicts coming due to the Assignment object & MCC changes

**Comment by wrandall22** [comment]
When I select a ministry, the MCC defaults to %s

**Comment by frett** [comment]
@wrandall22 I noticed that last night, haven't had a chance to look into how to handle it yet

**Comment by wrandall22** [comment]
Ok, fixed

**Comment by frett** [comment]
updated it to toggle the state of the MCC preference based on options available or not available

**Comment by frett** [comment]
I think I'm done with this PR.

**Comment by frett** [comment]
@wrandall22 @mattfred

**Comment by frett** [comment]
rebased off of master

**Comment by wrandall22** [comment]
Looks good to me.

**Pull request merged**
