### PR TITLE
release build preparation

### PR DESCRIPTION
**Pull request by frett**

### CODE REVIEW

**Comment by frett** [comment]
@wrandall22 @mattfred 

Should be ready to review

**Comment by mattfred** [comment]
Look Good.

**Comment by wrandall22** [comment]
With this update, how do we go about building it for debug purposes?

**Comment by frett** [comment]
debug should continue to work the same through Android Studio, you just won't be able to build the demo and release builds without the signing certs.

**Comment by frett** [comment]
if it is throwing errors when building debug let me know, I have some global gradle config on my machine that allows the demo and release builds. I want the debug build to continue to work without needing that global config.

**Comment by frett** [comment]
I know there are issues with updating the version of newrelic due to gradle & Android Studio caching stuff in memory. to reset gradle you just have to run `gradle -stop` from the command line and that should reset the in memory cache.

**Comment by frett** [comment]
@wrandall22 debug builds without global settings should be fixed

**Comment by wrandall22** [comment]
looks good to me

**Pull request merged**
