### PR TITLE
Churches

### PR DESCRIPTION
**Pull request by frett**

### CODE REVIEW

**Comment by frett** [comment]
@wrandall22 @mattfred 

Initial Churches support.
Includes:
- Church data model
- Background syncing of church data
- loading & display of churches on map

I still need to implement church drill down.

**Comment by frett** [comment]
depends on #32

**Comment by frett** [comment]
rebased for clarity

**Comment by mattfred** [comment]
@frett I was starting to work on drilling down for training, but I thought I would check with you to see how you are going to do the churches. I was starting a new activity with the training information. I know on the angular app it shows a dialog box but I don't know that a phone screen will be large enough for this. What do you think?

**Comment by frett** [comment]
@mattfred I was thinking of doing a DialogFragment, I figure a lot of this will be touched up by a UI designer at some point.

using the DialogFragment with a custom layout will allow us to handle it as a popup, but still fully utilize available space.

**Comment by mattfred** [comment]
OK. Thanks. This PR looks good to me.

**Comment by frett** [comment]
merging it in

**Pull request merged**
