### PR TITLE
[#MMAND-8] fix crash when loading session on gingerbread

### PR DESCRIPTION
**Pull request by frett**

### CODE REVIEW

**Comment by frett** [comment]
@wrandall22 @mattfred

**Comment by frett** [comment]
corresponding commit in gto-support:

https://github.com/GlobalTechnology/android-gto-support/commit/6c54e9f4e7fecf474b14d8fd7eba52aaa12a9583

**Comment by frett** [comment]
crash was an NPE while loading a session that didn't exist yet

**Comment by mattfred** [comment]
This looks good.

**Pull request merged**
